const actionTypes = {
    GET_HOME: 'GET_HOME',
    SET_CUR_SONG_ID: 'SET_CUR_SONG_ID',
    SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
    SET_CUR_ALBUM_ID: "SET_CUR_ALBUM_ID",
    SET_RECENT_SONG: "SET_RECENT_SONG",
    SEARCH: "SEARCH",
    CURRENT_WIDTH: "CURRENT_WIDTH",
    SET_RECENT: "SET_RECENT",

    // music
    PLAY: "PLAY",
    SET_ALBUM: 'SET_ALBUM',
    PLAYLIST: ' PLAYLIST',
    LOADING: 'LOADING',
    ZERO_SCROLL_TOP: "ZERO_SCROLL_TOP",
    ZERO_SCROLLTOP: "ZERO_SCROLLTOP",
}

export default actionTypes;